buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven {
            url "https://repo.maven.apache.org/maven2/"
        }
    }
    
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.0'
    }
}

plugins {
    id 'com.android.application' version '8.5.0' apply false
    id 'com.android.library' version '8.5.0' apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven {
            url "https://repo.maven.apache.org/maven2/"
        }
        maven {
            url "https://maven.google.com"
        }
    }
}

ext {
    minSdkVersion = 23
    targetSdkVersion = 34
    compileSdkVersion = 34
    buildToolsVersion = '34.0.0'
}
